---

- name: common | install unattended-upgrades
  tags:
  - package
  package:
    name: unattended-upgrades

- name: common | apt config
  tags:
  - config
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  loop:
  - 50unattended-upgrades
  - 60recommends

