---

- name: common | hostname | set name
  copy:
    dest: /etc/{{ item }}
    content: "{{ inventory_hostname ~ '.' ~ default_domain }}"
  loop:
  - hostname
  - mailname

- name: common | hostname | /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

