---

- name: common | hostname | set name
  hostname:
    name: "{{ inventory_hostname ~ '.' ~ default_domain }}"
  ignore_errors: yes

- name: common | hostname | set mailname
  copy:
    dest: /etc/mailname
    content: "{{ inventory_hostname ~ '.' ~ default_domain }}"

- name: common | hostname | /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

