---

- name: common | locale | locale.gen
  tags:
    - locale
  template:
    src: locale.gen.j2
    dest: /etc/locale.gen

- name: common | locale | gen
  tags:
    - locale
  locale_gen:
    name: "{{ item[0] }}"
  loop: "{{ locales }}"

- name: common | locale | default
  tags:
    - locale
  copy:
    dest: /etc/default/locale
    content: "LANG={{ locales[0][0] }}"
