---

- include_tasks: hostname.yml
  tags: 
  - hostname

- include_tasks: locale.yml
  tags: 
  - locale

- name: common | set timezone
  tags:
  - time
  timezone:
    name: "{{ timezone }}"

- include_tasks: apt.yml
  tags: 
  - apt
  when: ansible_pkg_mgr == "apt"

- include_tasks: less.yml
  tags: 
  - less

- include_tasks: htop.yml
  tags: 
  - htop

- include_tasks: kernel.yml
  tags: 
  - kernel
  when: use_backports_kernel

- include_tasks: modprobe.yml
  tags: 
  - kernel
  - modprobe
  when: modprobe_opts

- name: common | initramfs package
  tags:
  - package
  - initramfs
  package:
    name: initramfs-tools
  when: use_initramfs and ansible_virtualization_type != 'container' 

- name: common | enable TRIM on all mounted fs
  tags:
  - config
  - fstrim
  copy:
    src: fstrim.service
    dest: /etc/systemd/system/
  when: fstrim_all

- name: common | disable HDD write cache
  tags:
  - config
  - wce
  copy:
    src: 65-wce.rules
    dest: /etc/udev/rules.d/
  when: no_hdd_write_cache

