---

- name: common | install packages
  tags:
  - package
  package:
    name:
    - locales-all
    - unattended-upgrades
    - less
    - git
    - htop

- name: common | copy misc config
  tags:
  - config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - { src: htoprc, dest: /etc/ }
  - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/ }
  - { src: 60recommends, dest: /etc/apt/apt.conf.d/ }
  - { src: 71less.sh, dest: /etc/profile.d/ }

- name: common | set timezone
  tags:
  - time
  timezone:
    name: "{{ timezone }}"

- name: common | set locale
  tags:
  - locale
  copy:
    dest: /etc/default/locale
    content: "LANG={{ locale }}"

- include_tasks: hostname.yml
  tags: 
  - hostname

- include_tasks: kernel.yml
  tags: 
  - kernel
  when: ansible_virtualization_type != 'openvz' 

