---

- name: common | install packages
  tags:
  - package
  package:
    name:
    - locales-all
    - unattended-upgrades
    - less
    - git
    - htop

- name: common | copy misc config
  tags:
  - config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - { src: htoprc, dest: /etc/ }
  - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/ }
  - { src: 60recommends, dest: /etc/apt/apt.conf.d/ }
  - { src: 71less.sh, dest: /etc/profile.d/ }

- name: common | set hostname
  tags: 
  - config
  - hostname
  hostname:
    name: "{{ inventory_hostname ~ '.' ~ default_domain }}"
  ignore_errors: yes

- name: common | set mailname
  tags:
  - config
  - hostname
  copy:
    dest: /etc/mailname
    content: "{{ inventory_hostname ~ '.' ~ default_domain }}"

- name: common | /etc/hosts
  tags:
  - config
  - hostname
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: common | set timezone
  tags:
  - config
  - time
  timezone:
    name: "{{ timezone }}"

- name: common | set locale
  tags:
  - locale
  copy:
    dest: /etc/default/locale
    content: "LANG={{ locale }}"

- name: common | add backports repo
  tags:
  - apt
  apt_repository:
    repo: "{{ backports_source }}"
    filename: backports

- name: common | backports kernel
  tags:
  - kernel
  apt:
    default_release: "{{ backports_rel }}"
    name: linux-image-{{ arch }}
    only_upgrade: yes
  notify: restart networkd

