---

- name: common | copy misc config
  tags:
    - config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: vimrc, dest: /etc/vim/ }
    - { src: htoprc, dest: /etc/ }
    - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/ }
    - { src: 71less.sh, dest: /etc/profile.d/ }

- name: common | set hostname
  tags:
    - config
    - hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: common | /etc/hosts
  tags:
    - config
    - hostname
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: common | set timezone
  tags:
    - config
    - time
  timezone:
    name: "{{ timezone }}"
