---

- name: common | uninstall packages
  tags:
  - package
  package:
    name:
    - unattended-upgrades
    - htop

- name: common | remove config
  tags:
  - config
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - /etc/apt/apt.conf.d/50unattended-upgrades
  - /etc/apt/apt.conf.d/60recommends
  - /etc/htoprc
  - /etc/profile.d/71less.sh
  - /etc/apt/sources.list.d/backports.list
  - /etc/systemd/system/fstrim.service
  - /etc/udev/rules.d/65-wce.rules
